server:
  port: 8081

spring:
  application:
    name: trading-company-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master
  datasource:
    url: jdbc:mysql://localhost:3306/trading_companies
    username: root
    password: Abir@4545

springdoc:
 api-docs:
  path: /v3/api-docs
 swagger-ui:
  path: /swagger-ui.html

  

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"

keycloak:
  issuer: http://localhost:8080/realms/master
  realm: master
