CREATE DATABASE IF NOT EXISTS trading_companies;
CREATE DATABASE IF NOT EXISTS assets;
CREATE DATABASE IF NOT EXISTS traders;
CREATE DATABASE IF NOT EXISTS trade_orders;
CREATE DATABASE IF NOT EXISTS settlements;